### PR TITLE
Make V1 reader not discard trailing empty values

### PR DESCRIPTION
**Pull request by calmilamsy**
Fixes support for some jar mapping and merging stuff in cases related to pre 1.3.1 versions, which would be really nice to get working in upstream loom at some point, and this is the 0th step for getting that to be a reality.

### CODE REVIEW

**Comment by sfPlayer1** [comment]
How are you getting empty m.owner in there?

**Comment by calmilamsy** [comment]
> How are you getting empty m.owner in there?

Good question, I added that check in the wrong place. The result of `classMapper.map`, not the initial value of `m.owner` can be empty in the intermediary mappings that are widely used for b1.7.3 and 1.2.5 cursed fabric, due to server and client not 100% sharing classes.

[b1.7.3 merged intermediaries, if you're curious](https://gist.githubusercontent.com/Chocohead/b7ea04058776495a93ed2d13f34d697a/raw/Beta%201.7.3%20Merge.tiny)

**Comment by calmilamsy** [comment]
Well, this *technically* works, but there's no way this is getting merged, cause that'll hit performance noticeably.

**Comment by calmilamsy** [comment]
Yup, this works on the b1.7.3 merged intermediaries now

**Comment by sfPlayer1** [comment]
The current form looks acceptable, but the PR is still marked as draft

**Comment by sfPlayer1** [comment]
it doesn't build due to the copyright notice, please check

**Comment by calmilamsy** [comment]
> it doesn't build due to the copyright notice, please check

I'm guessing I need to add myself to the copyright header of the class I changed?

**Review by sfPlayer1 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
