### PR TITLE
Use Attributes#putValue instead of Attributes#put

### PR DESCRIPTION
**Pull request by ryuuta0217**
Attributes#put will only accept Attributes.Name, which will result in a ClassCastException.
https://docs.oracle.com/javase/8/docs/api/java/util/jar/Attributes.html#put-java.lang.Object-java.lang.Object-

### CODE REVIEW

**Review by sfPlayer1 — APPROVED** [review]
LGTM, thanks!

**Comment by sfPlayer1** [comment]
The license header is outdated, please run ./gradlew spotlessApply and commit+push to fix

**Comment by ryuuta0217** [comment]
tried but no changes detected :thinking:

**Comment by ryuuta0217** [comment]
:eyes:
I guess my first pull request turned out to be an embarrassing one...

**Review by modmuss50 — APPROVED** [review]

**Comment by sfPlayer1** [comment]
Don't worry, all good now :)

**Pull request merged**
